name    'graylog2-server'
version '0.0.1'
source 'UNKNOWN'
author 'Mick Pollard'
license 'Apache License, Version 2.0'
summary 'Manage graylog2-server'
description 'Graylog2-server module.'
project_page 'https://github.com/graylog2'
